workflows:
  android-workflow:
    name: Omar Estate Android
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Generate icons
        script: |
          mkdir -p android/app/src/main/res/mipmap-hdpi
          mkdir -p android/app/src/main/res/mipmap-mdpi
          mkdir -p android/app/src/main/res/mipmap-xhdpi
          mkdir -p android/app/src/main/res/mipmap-xxhdpi
          mkdir -p android/app/src/main/res/mipmap-xxxhdpi
          find android/app/src/main -name "*.png" -exec cp {} android/app/src/main/res/mipmap-hdpi/ic_launcher.png \;
          find android/app/src/main -name "*.png" -exec cp {} android/app/src/main/res/mipmap-mdpi/ic_launcher.png \;
          find android/app/src/main -name "*.png" -exec cp {} android/app/src/main/res/mipmap-xhdpi/ic_launcher.png \;
          find android/app/src/main -name "*.png" -exec cp {} android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png \;
          find android/app/src/main -name "*.png" -exec cp {} android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png \;
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
